[greeter]
background=/usr/share/nexusos/login.jpg
user-background=false
theme-name=Adwaita-dark
font-name=Inter 11
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~power
default-user-image=/usr/share/pixmaps/nexusos.png
