// The only functions Halcyon's own page can use. Web pages in the Browser never see this.
const { contextBridge, ipcRenderer } = require('electron');

const call = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('halcyon', {
  sysInfo: call('sys:info'),
  driveUsage: call('drive:usage'),
  list: call('fs:list'),
  readText: call('fs:readText'),
  writeText: call('fs:writeText'),
  writeBinary: call('fs:writeBinary'),
  readDataUrl: call('fs:readDataUrl'),
  unique: call('fs:unique'),
  mkdir: call('fs:mkdir'),
  rename: call('fs:rename'),
  trash: call('fs:trash'),
  addFromPC: call('fs:addFromPC'),
  copyToPC: call('fs:copyToPC'),
  copyIn: call('fs:copyIn'),
  open: call('shell:open'),
  reveal: call('shell:reveal'),
  external: call('shell:external'),
  winSettings: call('win:settings'),
  quit: call('app:quit'),
  isFullscreen: call('app:isFullscreen'),
  toggleFullscreen: call('app:fullscreen'),
  getLogin: call('app:getLogin'),
  setLogin: call('app:setLogin'),
  clock24: call('app:clock24'),
  usbSound: call('app:usbSound'),
  clips: { state: call('clips:state'), install: call('clips:install'), start: call('clips:start'), stop: call('clips:stop'), save: call('clips:save'), setCfg: call('clips:setCfg'), list: call('clips:list'), audio: call('clips:audio'), windows: call('clips:windows') },
  onClips: (fn) => ipcRenderer.on('clips', (_e, d) => fn(d)),
  nexa: { greet: call('nexa:greet'), misses: call('nexa:misses'), state: call('nexa:state'), install: call('nexa:install'), start: call('nexa:start'), remove: call('nexa:remove'), setCfg: call('nexa:setCfg'), history: call('nexa:history'),
    chat: call('nexa:chat'), stop: call('nexa:stopTalking'), speak: call('nexa:speak'), hear: call('nexa:hear') },
  uiSounds: call('app:uiSounds'),
  buddyCfg: call('buddy:cfg'), buddyAt: call('buddy:at'), bubbleSize: call('buddy:bubbleSize'), bubbleHide: call('buddy:bubbleHide'), buddyOpenNexa: call('buddy:openNexa'),
  onBuddy: (fn) => ipcRenderer.on('buddy', (_e, d) => fn(d)),
  onBubble: (fn) => { ipcRenderer.on('bubble', (_e, d) => fn('show', d)); ipcRenderer.on('bubble-say', (_e, d) => fn('say', d)); },
  lockKeysOsd: call('app:lockKeysOsd'), osdSize: call('osd:size'), onOsd: (fn) => ipcRenderer.on('osd', (_e, d) => fn(d)),
  onOpenChild: (fn) => ipcRenderer.on('open-child', (_e, d) => fn(d)),
  onNexa: (fn) => { ipcRenderer.on('nexa-stream', (_e, d) => fn('stream', d)); ipcRenderer.on('nexa-setup', (_e, d) => fn('setup', d)); ipcRenderer.on('nexa-state', (_e, d) => fn('state', d)); },
  onClipSaved: (fn) => ipcRenderer.on('clips-saved', (_e, d) => fn(d)),
  lx: (name, ...args) => ipcRenderer.invoke('lx', String(name), ...args),
  store: (name, ...args) => ipcRenderer.invoke('store', String(name), ...args),
  catalog: call('store:catalog'),
  answerPermission: (id, ok) => ipcRenderer.send('perm-answer', Number(id), !!ok),
  openWindow: call('win:open'),
  popup: call('win:popup'),
  popupHide: call('win:popupHide'),
  windows: call('win:list'),
  winAct: call('win:act'),
  toast: call('toast'),
  confirm: call('dlg:confirm'),
  toastSize: call('toast:size'),
  changed: call('sys:changed'),
  menu: (items) => ipcRenderer.invoke('menu', items),
  pins: call('pins:get'),
  setPins: call('pins:set'),
  binList: call('bin:list'),
  binRestore: call('bin:restore'),
  binDelete: call('bin:delete'),
  binEmpty: call('bin:empty'),
  copyTo: call('fs:copyTo'),
  moveTo: call('fs:moveTo'),
  newText: call('fs:newText'),
  stat: call('fs:stat'),
  setWallpaper: call('wall:set'),
  getWallpaper: call('wall:get'),
  clearWallpaper: call('wall:clear'),
  builtinWallpapers: call('wall:builtins'),
  useBuiltinWallpaper: call('wall:useBuiltin'),
  trayList: call('tray:list'),
  trayAct: call('tray:act'),
  trayMenu: call('tray:menu'),
  trayEvent: call('tray:event'),
  trayQuit: call('tray:quit'),
  quitFlatpak: call('app:quitFlatpak'),
  onTray: (fn) => ipcRenderer.on('tray', (_e, l) => fn(l)),
  onAppArg: (fn) => ipcRenderer.on('app-arg', (_e, a) => fn(a)),
  onPopup: (fn) => ipcRenderer.on('popup', (_e, w) => fn(w)),
  onPopupState: (fn) => ipcRenderer.on('popup-state', (_e, w) => fn(w)),
  onWindows: (fn) => ipcRenderer.on('windows', (_e, l) => fn(l)),
  onToast: (fn) => ipcRenderer.on('toast', (_e, d) => fn(d)),
  onUsb: (fn) => ipcRenderer.on('usb', (_e, d) => fn(d)),
  onChanged: (fn) => ipcRenderer.on('sys-changed', (_e, w) => fn(String(w))),
  onOpenUrl: (fn) => ipcRenderer.on('open-url', (_e, url) => fn(String(url))),
  onDownload: (fn) => ipcRenderer.on('download', (_e, d) => fn(d)),
  onJob: (fn) => ipcRenderer.on('job', (_e, d) => fn(d)),
  onPermission: (fn) => ipcRenderer.on('perm-ask', (_e, d) => fn(d)),
});
