// The only functions Halcyon's own page can use. Web pages in the Browser never see this.
const { contextBridge, ipcRenderer } = require('electron');

const call = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('halcyon', {
  sysInfo: call('sys:info'),
  driveUsage: call('drive:usage'),
  list: call('fs:list'),
  readText: call('fs:readText'),
  writeText: call('fs:writeText'),
  writeBinary: call('fs:writeBinary'),
  readDataUrl: call('fs:readDataUrl'),
  unique: call('fs:unique'),
  mkdir: call('fs:mkdir'),
  rename: call('fs:rename'),
  trash: call('fs:trash'),
  addFromPC: call('fs:addFromPC'),
  copyToPC: call('fs:copyToPC'),
  copyIn: call('fs:copyIn'),
  open: call('shell:open'),
  reveal: call('shell:reveal'),
  external: call('shell:external'),
  winSettings: call('win:settings'),
  quit: call('app:quit'),
  isFullscreen: call('app:isFullscreen'),
  toggleFullscreen: call('app:fullscreen'),
  getLogin: call('app:getLogin'),
  setLogin: call('app:setLogin'),
  clock24: call('app:clock24'),
  lx: (name, ...args) => ipcRenderer.invoke('lx', String(name), ...args),
  store: (name, ...args) => ipcRenderer.invoke('store', String(name), ...args),
  catalog: call('store:catalog'),
  answerPermission: (id, ok) => ipcRenderer.send('perm-answer', Number(id), !!ok),
  openWindow: call('win:open'),
  popup: call('win:popup'),
  popupHide: call('win:popupHide'),
  windows: call('win:list'),
  winAct: call('win:act'),
  toast: call('toast'),
  confirm: call('dlg:confirm'),
  toastSize: call('toast:size'),
  changed: call('sys:changed'),
  menu: (items) => ipcRenderer.invoke('menu', items),
  pins: call('pins:get'),
  setPins: call('pins:set'),
  binList: call('bin:list'),
  binRestore: call('bin:restore'),
  binDelete: call('bin:delete'),
  binEmpty: call('bin:empty'),
  copyTo: call('fs:copyTo'),
  moveTo: call('fs:moveTo'),
  newText: call('fs:newText'),
  stat: call('fs:stat'),
  setWallpaper: call('wall:set'),
  getWallpaper: call('wall:get'),
  clearWallpaper: call('wall:clear'),
  onAppArg: (fn) => ipcRenderer.on('app-arg', (_e, a) => fn(a)),
  onPopup: (fn) => ipcRenderer.on('popup', (_e, w) => fn(w)),
  onPopupState: (fn) => ipcRenderer.on('popup-state', (_e, w) => fn(w)),
  onWindows: (fn) => ipcRenderer.on('windows', (_e, l) => fn(l)),
  onToast: (fn) => ipcRenderer.on('toast', (_e, d) => fn(d)),
  onChanged: (fn) => ipcRenderer.on('sys-changed', (_e, w) => fn(String(w))),
  onOpenUrl: (fn) => ipcRenderer.on('open-url', (_e, url) => fn(String(url))),
  onDownload: (fn) => ipcRenderer.on('download', (_e, d) => fn(d)),
  onJob: (fn) => ipcRenderer.on('job', (_e, d) => fn(d)),
  onPermission: (fn) => ipcRenderer.on('perm-ask', (_e, d) => fn(d)),
});
